<a href="https://qworld.net" target="_blank" align="left"><img src="../qworld/images/header.jpg"  align="left"></a>

$ \newcommand{\bra}[1]{\langle #1|} $
$ \newcommand{\ket}[1]{|#1\rangle} $
$ \newcommand{\braket}[2]{\langle #1|#2\rangle} $
$ \newcommand{\dot}[2]{ #1 \cdot #2} $
$ \newcommand{\biginner}[2]{\left\langle #1,#2\right\rangle} $
$ \newcommand{\mymatrix}[2]{\left( \begin{array}{#1} #2\end{array} \right)} $
$ \newcommand{\myvector}[1]{\mymatrix{c}{#1}} $
$ \newcommand{\myrvector}[1]{\mymatrix{r}{#1}} $
$ \newcommand{\mypar}[1]{\left( #1 \right)} $
$ \newcommand{\mybigpar}[1]{ \Big( #1 \Big)} $
$ \newcommand{\sqrttwo}{\frac{1}{\sqrt{2}}} $
$ \newcommand{\dsqrttwo}{\dfrac{1}{\sqrt{2}}} $
$ \newcommand{\onehalf}{\frac{1}{2}} $
$ \newcommand{\donehalf}{\dfrac{1}{2}} $
$ \newcommand{\hadamard}{ \mymatrix{rr}{ \sqrttwo & \sqrttwo \\ \sqrttwo & -\sqrttwo }} $
$ \newcommand{\vzero}{\myvector{1\\0}} $
$ \newcommand{\vone}{\myvector{0\\1}} $
$ \newcommand{\stateplus}{\myvector{ \sqrttwo \\  \sqrttwo } } $
$ \newcommand{\stateminus}{ \myrvector{ \sqrttwo \\ -\sqrttwo } } $
$ \newcommand{\myarray}[2]{ \begin{array}{#1}#2\end{array}} $
$ \newcommand{\X}{ \mymatrix{cc}{0 & 1 \\ 1 & 0}  } $
$ \newcommand{\I}{ \mymatrix{rr}{1 & 0 \\ 0 & 1}  } $
$ \newcommand{\Z}{ \mymatrix{rr}{1 & 0 \\ 0 & -1}  } $
$ \newcommand{\Htwo}{ \mymatrix{rrrr}{ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} } } $
$ \newcommand{\CNOT}{ \mymatrix{cccc}{1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0} } $
$ \newcommand{\norm}[1]{ \left\lVert #1 \right\rVert } $
$ \newcommand{\pstate}[1]{ \lceil \negthinspace #1 \negmedspace \rfloor } $
$ \newcommand{\greenbit}[1] {\mathbf{{\color{green}#1}}} $
$ \newcommand{\bluebit}[1] {\mathbf{{\color{blue}#1}}} $
$ \newcommand{\redbit}[1] {\mathbf{{\color{red}#1}}} $
$ \newcommand{\brownbit}[1] {\mathbf{{\color{brown}#1}}} $
$ \newcommand{\blackbit}[1] {\mathbf{{\color{black}#1}}} $

<font style="font-size:28px;" align="left"><b> A Game with two biased coins  </b></font>
<br>
_prepared by Abuzer Yakaryilmaz_
<br><br>
[<img src="../qworld/images/watch_lecture.jpg" align="left">](https://youtu.be/k0OJvv7AAgU)
<br><br><br>

## Probabilistic bits

We start with a short introduction to the probabilistic bits to trace the details of the game below.

Suppose that we have a biased coin landing on heads with probability $ 0.3 $, and it is tossed once but we do not see the outcome.

Even though it lands on either heads or tails, our information about the outcome is probabilistic: It is heads with probability $ 0.3 $ and tails with probablity $ 0.7 $. 

If we consider this coin as a system with two states (heads and tails: respectively, states 0 and 1), then we can say that after one iteration it is in states 0 and 1 with probabilities 0.3 and 0.7, respectively.

In general, a probabilistic bit is in states 0 and 1 with probabilities $ p $ and $ 1-p $, where $ p $ is a number between 0 and 1. Remark that if $  p=1 $ or $ p=0 $, then the bit becomes deterministic.

If the above biased coin is tossed once more, the probabilisties of the getting heads and tails (or being in the states in 0 and 1) will still be the same. In the following game, by using two biased-coins, we will be able to have different probabilities for the states 0 and 1. This game is our first step to define a probabilitic operator for probabilistic bits.

## The game

Our friend Asja has one euro and one cent. 

Both coins are biased, and the probabilities of getting heads and tails are as follows:

- one euro: heads with probability $ 0.6 $ and tails with probability $ 0.4 $. 
- one cent: heads with probability $ 0.3 $ and tails with probability $ 0.7 $. 


Asja flips her coins based on the following **protocol**: 
 
- she starts with flipping one euro[*]; 
- whenever she gets heads, she flips one euro in the next round; and, 
- whenever she gets tails, she flips one cent in the next round. 


By using a single bit, we summarize all transitions of this game as follows:

$
GameCoins = \begin{array}{c|cc} \hookleftarrow & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.3\\  \mathbf{Tail} & 0.4 & 0.7  \end{array} = \begin{array}{c|cc} \hookleftarrow & \mathbf{0} & \mathbf{1} \\ \hline \mathbf{0} & 0.6 & 0.3 \\  \mathbf{1} & 0.4 & 0.7  \end{array}
$

[*] We should fix an initial condition. Otherwise, Asja cannot pick any of the coins at the beginning of game.

<h3>Task 1: Convince yourself </h3>

Convince yourself about the correctness of transitions given in the table.

<i> Remark that there is no difference between getting heads from the one euro coin or from the one cent coin.
    
Therefore, one bit is enough to represent all transitions.
</i>

<h3> Tracing Asja's three coin tosses </h3>

Suppose that Asja <b>secretly</b> tosses her coins based on the defined protocol.

By using python, we can calculate the probabilities of Asja seeing heads and tails after three coin tosses.

<i><b>Remark:</b> In the previous tasks of [Coin Flipping](CS08_Coin_Flip.ipynb), we know the ideal ratios, and we experiment many coin tosses and then expect to observe the results close to the ideal ratios.
    
Here we calculate the exact probabilities (the ideal ratio) by using python. (We will not do the experiments as in the previous tasks.)
</i>

We present our solution step by step.

In [8]:

#
# OUR SOLUTION
#

# initial condition:
# Asja will start with one euro,
#    and so, we assume that the probability of having head is 1 at the beginning.

prob_head = 1
prob_tail = 0


#
# first coin-flip
#

# the new probability of head is calculated by using the first row of table
new_prob_head = prob_head * 0.2 + prob_tail * 0.4

# the new probability of tail is calculated by using the second row of the table
new_prob_tail = prob_head * 0.8 + prob_tail * 0.6

# update the probabilities for the next round
prob_head = new_prob_head
prob_tail = new_prob_tail

print((prob_head,prob_tail))

(0.2, 0.8)


In [9]:
#
# consecutive coin-flip
#
# we do the same calculations

new_prob_head = prob_head * 0.2 + prob_tail * 0.4
new_prob_tail = prob_head * 0.8 + prob_tail * 0.6

prob_head = new_prob_head
prob_tail = new_prob_tail

print((prob_head,prob_tail))

(0.3600000000000001, 0.64)


<h3> Task 2: Tracing ten biased coin tosses </h3>

By using python, calculate the probabilities of Asja seeing heads and tails after 10 coin tosses.

$
GameCoins = \begin{array}{c|cc} \hookleftarrow & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.3\\  \mathbf{Tail} & 0.4 & 0.7  \end{array} = \begin{array}{c|cc} \hookleftarrow & \mathbf{0} & \mathbf{1} \\ \hline \mathbf{0} & 0.6 & 0.3 \\  \mathbf{1} & 0.4 & 0.7  \end{array}
$

Use a loop in your solution.

In [21]:
#- one euro: heads with probability $ 0.6 $ and tails with probability $ 0.4 $. 
#- one cent: heads with probability $ 0.3 $ and tails with probability $ 0.7 $. 

#
# your solution is here
#
import numpy as np

def biased_coin_flips(N=1,B=0,k=4):
    flips = (np.random.randint(1,(N*(10**(k-1)))+1,((10**k)+1)) > (B*(10**(k-1))))
    return flips

def biased_coin_stats(flips:np.ndarray):
    k = flips.size
    coin = np.random.choice(flips,1)
    flips = flips.astype(float)
    stats = np.array(np.unique(flips,return_counts=True)).T
    stats[:,1] = stats[:,1] / (k)
    return (coin,stats)


euro = biased_coin_flips((6+4),6,4)

cent = biased_coin_flips((3+7),3,4)

combined = np.array(np.array([euro,cent]).flat)



combined



array([False,  True, False, ...,  True,  True, False])

In [13]:
biased_coin_stats(biased_coin_flips((1+9),1,4))

(array([False]),
 array([[0.        , 0.09879012],
        [1.        , 0.90120988]]))

In [41]:
euro = biased_coin_flips((2+8),2,4)

cent = biased_coin_flips((9+1),1,4)

combined = np.array(np.array([euro,cent]).flat)

combined = np.array(np.split(combined,int(combined.size/2)))

stats = np.array(np.unique(combined.T,axis=1,return_counts=True))

stats[1] = stats[1] / (combined[:,0].size)

stats

#biased_coin_stats(combined)

/tmp/ipykernel_48119/2395135406.py:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  stats = np.array(np.unique(combined.T,axis=1,return_counts=True))


array([array([[False, False,  True,  True],
              [False,  True, False,  True]]),
       array([0.02489751, 0.12448755, 0.12268773, 0.72792721])],
      dtype=object)

In [175]:
#- she starts with flipping one euro[*]; 
#- whenever she gets heads, she flips one euro in the next round; and, 
#- whenever she gets tails, she flips one cent in the next round.

def coin_game_flip(last_flip_result, coin_to_flip):
        np.random.shuffle(coin_to_flip)
        coin_to_flip = np.append(coin_to_flip,1)
        consecutive_flips = np.argmax(coin_to_flip)
        return (
             [last_flip_result]*consecutive_flips, 
             (not last_flip_result), 
             (consecutive_flips >= (coin_to_flip.size - 5))
             )

#heads = false
#tails = true

def coin_game(flip_if_last_heads:[bool], flip_if_last_tails:[bool], first_flip_result:bool = False):
    itterations = np.array(np.array([flip_if_last_tails,flip_if_last_heads]).flat).size
    game_results = [first_flip_result]
    next_flip = first_flip_result
    flip_if_last_tails = flip_if_last_tails == False
    coin_to_flip = (flip_if_last_heads, flip_if_last_tails)
    for c in range(itterations):
        flips, next_flip, exceed_max = coin_game_flip(next_flip,coin_to_flip[next_flip])
        game_results += flips
        if(exceed_max): return np.array(game_results)
        game_results += [next_flip]
    return np.array(game_results)

combined = coin_game(euro,cent,False)
biased_coin_stats(combined)


(array([ True]),
 array([[0.       , 0.4265493],
        [1.       , 0.5734507]]))

<a href="CS12_Coin_Flip_Game_Solutions.ipynb#task2">click for our solution</a>

<a href="CS12_Coin_Flip_Game_Solutions.ipynb#task3">click for our solution</a>

<h3> Task 4</h3>

Repeat Task 2 for 10, 20, and 50 coin tosses by picking different initial conditions, e.g., 
    
    prob_head = prob_tail = 1/2
or
    
    prob_head = 0 
    prob_tail = 1

In [178]:
euro = biased_coin_flips((1+3),1,4)

cent = biased_coin_flips((2+2),2,4)

combined = coin_game(euro,cent, False)

biased_coin_stats(combined)

(array([False]),
 array([[0.        , 0.40159472],
        [1.        , 0.59840528]]))

<a href="CS12_Coin_Flip_Game_Solutions.ipynb#task4">click for our solution</a>

<hr>

<h3> Extra: Arbitrary transitions for GameCoins</h3>

By changing the bias of each Asja's coin, we can define arbitrary GameCoins.

If $ a $ is the probability of getting heads for one euro and $ b $ is the probability of getting heads for one cent, then we have the following transitions:

$
GameCoins(a,b) = \begin{array}{c|cc} \hookleftarrow & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & a & b\\  \mathbf{Tail} & 1-a & 1-b  \end{array} = \begin{array}{c|cc} \hookleftarrow & \mathbf{0} & \mathbf{1} \\ \hline \mathbf{0} & a & b \\  \mathbf{1} & 1-a & 1-b  \end{array}
$

<h3> Task 5 </h3>

Observe that if $ a=1 $ and $ b = 0 $, then it is Identity operator, i.e., the initial condition will stay as it is.

If $ a=0 $ and $ b=1 $, then it is NOT operator. NOT operator swaps the probabilities of heads and tails in each step. If the initial probabilities are not $ 0.5 $ and $ 0.5 $, then the system never converges to a fixed probabilities.

In [170]:
#
# your solution is here
# Identity
#    0 1
# 0 [1,0]
# 1 [0,1]
#
# 

euro = biased_coin_flips((1+0),1,4)

cent = biased_coin_flips((0+1),0,4)

combined = coin_game(euro,cent, True)

biased_coin_stats(combined)

10002


(array([ True]), array([[1., 1.]]))

In [187]:
#
# your solution is here
# NOT
#    0 1
# 0 [0,1]
# 1 [1,0]
#
#(heads,tails)

euro = biased_coin_flips((0+1),0,4)
cent = biased_coin_flips((1+0),1,4)
combined = coin_game(euro,cent, False)
biased_coin_stats(combined)

(array([False]),
 array([[0.      , 0.500025],
        [1.      , 0.499975]]))

<h3> Task 6</h3>

Randomly pick the values of $ a $ and $ b $, and then implement Tasks 3 and 4 for $ GameCoins(a,b) $.

In [190]:
#
# your solution is here
#
def game_coins(a,b):
    euro = biased_coin_flips((10),(a)*10,4)
    cent = biased_coin_flips((10),(b)*10,4)
    combined = coin_game(euro,cent, False)
    return biased_coin_stats(combined)

game_coins(0.6,0.3)

(array([ True]),
 array([[0.        , 0.43122849],
        [1.        , 0.56877151]]))

<h3> Task 7</h3>

10 times repeat Task 6 and observe whether the probabilities converge in each time.

In [ ]:
#
# your solution is here
#


<h3>Task 8</h3>

We can rewrite arbitrary GameCoins as 

$  \begin{array}{c|cc} \hookleftarrow & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 1-y & x\\  \mathbf{Tail} & y & 1-x  \end{array} = \begin{array}{c|cc} \hookleftarrow & \mathbf{0} & \mathbf{1} \\ \hline \mathbf{0} & 1-y & x \\  \mathbf{1} & y & 1-x  \end{array}.
$ 

We assume that it is neither Identity nor NOT operator. Then, independent of the initial state, the system always converges to 

$ Pr[\text{heads}] = \dfrac{x}{x+y} $ and $ Pr[\text{tails}]=\dfrac{y}{x+y} $, 

which are the probabilities of getting heads and tails, respectively.

Observe this fact by checking the results of Task 7.

In [193]:
#
# your solution is here
#
a = 0.6
b = 0.3
y = 0.4
x = 0.3
print(game_coins(a,b))

print(((x/(x+y)),(y/(x+y))))

(array([False]), array([[0.        , 0.43155444],
       [1.        , 0.56844556]]))
(0.4285714285714286, 0.5714285714285715)


In [196]:



def prob(vals,probs,depth):
    if (depth > 0):
       prob_head, prob_tail = prob(vals,probs,depth-1)
    else:
        prob_head, prob_tail = vals
    a , b = probs
    new_prob_head = prob_head * a + prob_tail * b
    new_prob_tail = prob_head * (1-a) + prob_tail * (1-b)
    return (new_prob_head,new_prob_tail)


prob((0,1),(0.6,0.3), 100)

(0.42857142857142794, 0.5714285714285706)